Add Followers component tests
ehnat0n/webdriver-github-search pull request #4
Opened 2023-12-10 20:41 UTC by ehnat0n

PR covers the story for Followers component: https://amonteschool.atlassian.net/browse/GTHB004-16

Known bugs:
1. Misleading information in "Followers" on page load/refresh. Bug report: https://amonteschool.atlassian.net/browse/GTHB004-92
2. Followers component capitalizes first letter of every follower listed. Bug report: https://amonteschool.atlassian.net/browse/GTHB004-93
3. Delayed user info update after refresh (same bug affects User Info component). https://amonteschool.atlassian.net/browse/GTHB004-91

2023-12-14 03:13 UTC, galiur commented on pom/components/base_element.py
> +        return self.wait.until(ec.visibility_of_element_located(locator))
Why do you use 2 'return' statements here? Can't you just use:
`return self.wait.until(ec.visibility_of_element_located(locator))`
cause this method already checks for presence of a element on the page

2023-12-14 03:15 UTC, galiur commented on pom/components/base_element.py
> +        return self.wait.until(ec.visibility_of_all_elements_located(locator))
Same questions here

2023-12-14 03:55 UTC, galiur requested changes
Ok, I couldn't understand everything that you did but I tried to do my best! ) Cause I'm still not that good at so many topics. It's hard to read even your own code sometimes.

2023-12-14 05:34 UTC, ehnat0n commented on pom/components/base_element.py
> +        return self.wait.until(ec.visibility_of_element_located(locator))
Yeah. I created 2nd method to have both options - wait for element presence and for element visibility (on top of presence). But just copy pasted the code originally and forgot to change the wait.

So in this commit I replaced presence with visibility for second set of methods. Now there is one "find_element" that just uses the wait for presence. And this new "find_visible_element" that waits for visibility.

2023-12-14 05:34 UTC, ehnat0n commented on pom/components/base_element.py
> +        return self.wait.until(ec.visibility_of_all_elements_located(locator))
Same as above - red one removed because was copy paste and green one added instead.

2023-12-14 17:30 UTC, galiur approved these changes

2023-12-15 01:52 UTC, In-Anna commented on features/environment.py
>      # Creating instances to work with app components
Haven't found a usage of context.wait anywhere in steps (and was not expecting).
Better to move this WebDriverWait(context.browser, EXPLICIT_WAIT) to Base and you might not need context.wait at all

2023-12-15 03:19 UTC, In-Anna commented on features/environment.py
> +    context.user_followers_element = Followers(context)
No need to create instances here - only where you need it

2023-12-15 15:45 UTC, In-Anna approved these changes

2023-12-16 03:40 UTC, merged