Search field feature tests
ehnat0n/webdriver-github-search pull request #5
Opened 2023-12-11 02:11 UTC by galiur

PR covers the story for Search field component: https://amonteschool.atlassian.net/jira/software/projects/GTHB004/boards/13?selectedIssue=GTHB004-9

Known bugs:

1. Searching for not existing user does not populate empty results. Bug report: https://amonteschool.atlassian.net/browse/GTHB004-94
2. Searching with an empty value does not populate empty results. Bug report: https://amonteschool.atlassian.net/browse/GTHB004-95

2023-12-12 03:52 UTC, ehnat0n requested changes
Take a look Ravil, we can have a call if you need more details.

2023-12-12 03:52 UTC, ehnat0n commented on features/search_field.feature
> +    Then Wait for 3 seconds
This wait is ok if you want to do visual verification while working on the scenario, but when it's ready we can remove.

Most likely these test suites would be run remotely - makes no difference for you, but will slow down automation.

2023-12-12 03:52 UTC, ehnat0n commented on features/search_field.feature
> +    And I search an empty value
If we look at the step implementation it is pretty much identical to "I search for not existing user using Enter Key", just the user name is empty string "   ".

I think we should consider 2 options here:
- use one method for two step definitions with default non-existing user name " "
- set it up in the same way as for other scenarios ("I set username as `<one space here>` and save it to user_name

2023-12-12 03:52 UTC, ehnat0n commented on features/search_field.feature
>      And I search for user using Enter Key
Let's call these methods either "search for existing/non-existing user" or "search for valid/invalid user". Difference would be the wait that we are doing to get the desired result.

And later it gives us potential to refactor and combine 2 methods into 1 with a key-word check.

2023-12-12 03:52 UTC, ehnat0n commented on features/search_field.feature
>      Then Wait for 3 seconds
While bug is here no need to wait - it's gonna sit there for 5 seconds because of the Explicit Wait we have set up by default.

2023-12-12 03:52 UTC, ehnat0n commented on features/steps/browser.py
> +    context.search_field_element.search_for_user_with_key("   ")
Just do a single space - minimal value that qualifies for "empty value". Because what if the test passes with 3 spaces, but fails with 1? :)

2023-12-12 03:52 UTC, ehnat0n commented on pom/locators.py
> +    SEARCH_RESULTS = (By.XPATH, "//section[2]|//section[3]")
Nit-picking a bit, but I'd add a space around or "|" for readability.

2023-12-12 04:12 UTC, ehnat0n commented on features/search_field.feature
> +    And I search an empty value
`    try:
        var_name = context.table.headings[0]
    except AttributeError:
        user_name = " "
    else:
        user_name = eval(var_name)`

2023-12-14 04:02 UTC, galiur commented on features/search_field.feature
> +    Then Wait for 3 seconds
Thank you! Great point! Your reviews are just awesome! Very helpful!

2023-12-14 04:06 UTC, galiur commented on pom/locators.py
> +    SEARCH_RESULTS = (By.XPATH, "//section[2]|//section[3]")
No, it's not. Thank you!

2023-12-14 04:08 UTC, galiur commented on features/search_field.feature
>      And I search for user using Enter Key
Very good suggestion! Will do the "existing/non-existing" one!

2023-12-16 04:37 UTC, closed without merging

2023-12-16 04:49 UTC, ehnat0n commented
Closed this version because we re-based local branch on main and did another PR #7: https://github.com/ehnat0n/webdriver-github-search/pull/7